In [2]:
# Gradient descent is a method of optimization of using gradient while estimating the weighhts. 
# It is a general method which works in almost all the cases even in dummy variables trap scenariof for categorical
# variables.
# Below is the equation of gradient descent: 
# w_new = w_old + (learning_rate * gradient_at_w_old)

In [11]:
import numpy as np
import matplotlib.pyplot as plt

# Number of records
N = 10
# Number of dimensions 
D = 3

# Generating the numbers
X = np.zeros((N, D))
X[:, 0] = 1
X[:5, 1] = 1
X[5:, 2] = 1

Y = np.array([0]*5 + [1]*5)

print("X: ", X)

X:  [[1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]]
